# Generated by Django 3.1.6 on 2022-01-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchnumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='fio_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
