# Generated by Django 3.2 on 2022-11-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('success', 'Success'), ('timeout', 'Timeout'), ('unicode', 'Unicode'), ('unexpected', 'Unexpected'), ('process', 'Process')], max_length=100)),
            ],
            options={
                'db_table': 'doc_status',
            },
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('filepath', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docstatusmodel')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ParagraphsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentsmodel')),
            ],
            options={
                'db_table': 'paragraphs',
            },
        ),
        migrations.CreateModel(
            name='TelephonesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name=50)),
                ('number_integer', models.BigIntegerField()),
                ('paragraph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paragraphsmodel')),
            ],
            options={
                'db_table': 'telephones',
            },
        ),
        migrations.CreateModel(
            name='SurnamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('paragraph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paragraphsmodel')),
            ],
            options={
                'db_table': 'surnames',
            },
        ),
    ]
