# Generated by Django 4.2.1 on 2023-05-19 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocExtensionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extension", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "doc_extensions",
            },
        ),
        migrations.CreateModel(
            name="SettingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_ip",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}:[1-9][0-9]{0,6}$"
                            )
                        ],
                    ),
                ),
                ("db_port", models.IntegerField()),
                ("db_path", models.CharField(max_length=300)),
                ("db_login", models.CharField(max_length=100)),
                ("db_password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
