# Generated by Django 3.2 on 2022-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentsmodel',
            index=models.Index(fields=['date'], name='documents_date_11c106_idx'),
        ),
        migrations.AddIndex(
            model_name='surnamesmodel',
            index=models.Index(fields=['name'], name='surnames_name_99dcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='surnamesmodel',
            index=models.Index(fields=['patronymic'], name='surnames_patrony_3d2f28_idx'),
        ),
        migrations.AddIndex(
            model_name='surnamesmodel',
            index=models.Index(fields=['surname'], name='surnames_surname_67a3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='telephonesmodel',
            index=models.Index(fields=['number_integer'], name='telephones_number__987a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='telephonesmodel',
            index=models.Index(fields=['number'], name='telephones_number_45a49b_idx'),
        ),
    ]
