# Generated by Django 4.2.1 on 2023-05-19 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docextensionmodel",
            options={"verbose_name": "extension", "verbose_name_plural": "extensions"},
        ),
        migrations.AlterModelOptions(
            name="settingsmodel",
            options={"verbose_name": "settings", "verbose_name_plural": "settings"},
        ),
    ]
