# Generated by Django 3.2 on 2022-11-28 13:33

from django.db import migrations, models
from api.models import DocStatusModel


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    doc_status_create_list = []
    doc_status = apps.get_model("api", "DocStatusModel")
    for choice in DocStatusModel.StatusChoices.choices:
        doc_status_create_list.append(doc_status(status_name=choice[0]))
    db_alias = schema_editor.connection.alias
    doc_status.objects.using(db_alias).bulk_create(doc_status_create_list)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    doc_status_create_list = []
    doc_status = apps.get_model("api", "DocStatusModel")
    for choice in DocStatusModel.StatusChoices.choices:
        doc_status_create_list.append(choice[0])
    db_alias = schema_editor.connection.alias
    doc_status.objects.using(db_alias).filter(status_name__in=doc_status_create_list).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221128_1220'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

