# Generated by Django 4.2.1 on 2023-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_docextensionmodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(max_length=100, verbose_name="documents status name"),
                ),
            ],
            options={
                "verbose_name": "doc status",
                "verbose_name_plural": "doc status",
                "db_table": "doc_status",
            },
        ),
    ]
