# Generated by Django 3.2 on 2022-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221128_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsmodel',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='paragraphsmodel',
            old_name='doc_id',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='surnamesmodel',
            old_name='paragraph_id',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='telephonesmodel',
            old_name='paragraph_id',
            new_name='paragraph',
        ),
    ]
