# Generated by Django 4.2.1 on 2023-05-19 09:58

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_docstatusmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proj_type",
                    models.CharField(
                        choices=[("SR", "Search proj"), ("RF", "Refresh proj")],
                        default="SR",
                        max_length=100,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                ("is_start", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "project setting",
                "verbose_name_plural": "projects settings",
                "db_table": "project_settings",
            },
        ),
        migrations.AlterField(
            model_name="docextensionmodel",
            name="extension",
            field=models.CharField(max_length=30, verbose_name="extension name"),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="db_ip",
            field=models.CharField(
                max_length=100,
                validators=[api.validators.ip_validator],
                verbose_name="database ip",
            ),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="db_login",
            field=models.CharField(max_length=100, verbose_name="database login"),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="db_password",
            field=models.CharField(max_length=100, verbose_name="database password"),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="db_path",
            field=models.CharField(max_length=300, verbose_name="database path"),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="db_port",
            field=models.IntegerField(verbose_name="db port"),
        ),
    ]
