# Generated by Django 3.2 on 2022-12-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221128_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_ip', models.GenericIPAddressField()),
                ('db_port', models.IntegerField()),
                ('db_path', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
