# Generated by Django 3.2 on 2022-12-07 20:22
from api.models import SettingsModel
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    settings_model = apps.get_model("api", "SettingsModel")
    SettingsModel(db_ip='127.0.0.1', db_port='5432', )
    for choice in DocStatusModel.StatusChoices.choices:
        doc_status_create_list.append(doc_status(status_name=choice[0]))
    db_alias = schema_editor.connection.alias
    doc_status.objects.using(db_alias).bulk_create(doc_status_create_list)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    doc_status_create_list = []
    doc_status = apps.get_model("api", "DocStatusModel")
    for choice in DocStatusModel.StatusChoices.choices:
        doc_status_create_list.append(choice[0])
    db_alias = schema_editor.connection.alias
    doc_status.objects.using(db_alias).filter(status_name__in=doc_status_create_list).delete()


class Migration(migrations.Migration):



    dependencies = [
        ('api', '0005_settingsmodel'),
    ]

    operations = [


    ]
