# Generated by Django 4.2.1 on 2023-05-19 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_projectssettings_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectssettings",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="project id"),
        ),
    ]
