# Generated by Django 4.2.1 on 2023-05-19 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_projectssettings_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectssettings",
            name="id",
        ),
        migrations.AlterField(
            model_name="projectssettings",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="project id",
            ),
        ),
    ]
