# Generated by Django 3.2 on 2022-12-07 20:29
from api.models import SettingsModel
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    settings_model = apps.get_model("api", "SettingsModel")
    settings_model.objects.using(db_alias).create(id=1, db_ip='127.0.0.1', db_port='5432', db_login='django',
                                                  db_path='osa_extra',
                                                  db_password='django')


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    db_alias = schema_editor.connection.alias
    settings_model = apps.get_model("api", "SettingsModel")
    settings_model.objects.using(db_alias).filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20221207_2028'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
