# Generated by Django 4.2.1 on 2023-05-19 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_projectssettings_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectssettings",
            old_name="uuid",
            new_name="id",
        ),
    ]
