# Generated by Django 3.2 on 2022-12-11 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221207_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='db_ip',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}:[1-9][0-9]{0,6}$')]),
        ),
    ]
