# Generated by Django 4.2.1 on 2023-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_rename_uuid_projectssettings_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500, verbose_name="filename")),
                (
                    "filepath",
                    models.CharField(max_length=1000, verbose_name="filepath"),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, null=True, verbose_name="document date"),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.docstatusmodel",
                        verbose_name="doc status",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "db_table": "documents",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ParagraphsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="paragraph text")),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="api.documentsmodel",
                        verbose_name="documents",
                    ),
                ),
            ],
            options={
                "verbose_name": "paragraph",
                "verbose_name_plural": "paragraphs",
                "db_table": "paragraphs",
            },
        ),
        migrations.CreateModel(
            name="TelephonesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="telephones")),
                (
                    "number_integer",
                    models.BigIntegerField(verbose_name="integer telephones"),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telephones",
                        to="api.paragraphsmodel",
                        verbose_name="paragraph",
                    ),
                ),
            ],
            options={
                "verbose_name": ("telephone",),
                "verbose_name_plural": ("telephones",),
                "db_table": "telephones",
                "indexes": [
                    models.Index(fields=["number_integer"], name="telephones_number__987a1e_idx"),
                    models.Index(fields=["number"], name="telephones_number_45a49b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurnamesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("patronymic", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.paragraphsmodel",
                    ),
                ),
            ],
            options={
                "db_table": "surnames",
                "indexes": [
                    models.Index(fields=["name"], name="surnames_name_99dcd5_idx"),
                    models.Index(fields=["patronymic"], name="surnames_patrony_3d2f28_idx"),
                    models.Index(fields=["surname"], name="surnames_surname_67a3f6_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documentsmodel",
            index=models.Index(fields=["date"], name="documents_date_11c106_idx"),
        ),
    ]
