# Generated by Django 3.2 on 2022-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_projectssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectssettings',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
