# Generated by Django 3.2 on 2022-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_projectssettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocExtensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'doc_extensions',
            },
        ),
        migrations.AlterModelTable(
            name='projectssettings',
            table='project_settings',
        ),
    ]
