# Generated by Django 3.2 on 2022-12-12 14:55
from api.models import DocExtensionModel
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    doc_extensions_list = []
    db_alias = schema_editor.connection.alias
    doc_extensions = apps.get_model("api", "DocExtensionModel")
    for choice in DocExtensionModel.ExtensionChoices.choices:
        doc_extensions_list.append(DocExtensionModel(extension=choice[0]))
    doc_extensions.objects.using(db_alias).bulk_create(doc_extensions_list)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    db_alias = schema_editor.connection.alias
    doc_extensions = apps.get_model("api", "DocExtensionModel")
    doc_extensions.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221212_1454'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
