# Generated by Django 3.2 on 2022-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20221212_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docextensionmodel',
            name='extension',
            field=models.CharField(choices=[('doc', 'Doc'), ('docx', 'Docx'), ('xls', 'Xls'), ('xlsx', 'Xlsx'), ('txt', 'Txt'), ('rtf', 'Rtf'), ('csv', 'Csv')], max_length=30),
        ),
    ]
