# Generated by Django 3.2 on 2022-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_docextensionmodel_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectssettings',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
