# Generated by Django 3.2 on 2022-12-12 19:10
from api.models import ProjectsSettings
from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    project_settings = apps.get_model("api", "ProjectsSettings")
    ProjectsSettings.objects.using(db_alias).create(proj_type='extract_entity_proj')
    ProjectsSettings.objects.using(db_alias).create(proj_type='retrain_proj')


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    db_alias = schema_editor.connection.alias
    project_settings = apps.get_model("api", "ProjectsSettings")
    project_settings.objects.using(db_alias).all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_projectssettings_is_start'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
