# Generated by Django 3.2 on 2022-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20221212_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
