# Generated by Django 3.2 on 2022-12-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userrequestslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequestsList',
        ),
    ]
