files: 'back*'
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=100, back]
        language_version: python3.11

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        args: [--config=back/.flake8, back]
        language_version: python3.11
