# Generated by Django 3.1.6 on 2021-04-15 17:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('server_name', models.TextField()),
                ('path2base', models.TextField()),
                (
                    'path2log',
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location='/media/gravity/Data/PycharmProjects/get_phone_view_git/logfiles'
                        ),
                        upload_to='',
                    ),
                ),
                ('path2files', models.TextField(blank=True, null=True)),
                ('is_run', models.BooleanField(default=False)),
                ('project_id', models.TextField(default='')),
                ('port', models.IntegerField()),
            ],
            options={
                'db_table': 'project_settings',
            },
        ),
    ]
