# Generated by Django 3.1.6 on 2021-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='path2base',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='port',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='server_name',
        ),
    ]
