# Generated by Django 3.1.6 on 2021-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210416_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='time_processing',
            field=models.IntegerField(default=0),
        ),
    ]
