# Generated by Django 3.1.6 on 2022-02-14 07:50

from django.db import migrations, models
import django.db.models.deletion


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # models.QuestionHistory(numbers_json=numbers_list).save()
    ProjectType = apps.get_model("index", "ProjectType")
    ProjectType.objects.create(proj_name='extracting named entities')


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220112_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('proj_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'proj_type',
            },
        ),
        migrations.RunPython(combine_names),
        migrations.RemoveField(
            model_name='projectsettings',
            name='is_run',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='path2files',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='path2log',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='thread_count',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='time_processing',
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='proj_settings',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='proj_type',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='index.projecttype'
            ),
            preserve_default=False,
        ),
    ]
