# Generated by Django 3.1.6 on 2022-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220214_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='is_run',
            field=models.BooleanField(default=False),
        ),
    ]
