# Generated by Django 3.1.6 on 2022-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_projectsettings_is_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='project_id',
            field=models.TextField(default=''),
        ),
    ]
