# Generated by Django 3.1.6 on 2022-02-16 07:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_projectsettings_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='log_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/gravity/Data/PycharmProjects/get_phone_view_git/logfiles'), upload_to=''),
        ),
    ]
