# Generated by Django 3.1.6 on 2022-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_projectsettings_log_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=100)),
            ],
        ),
    ]
