# Generated by Django 4.2.1 on 2023-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0013_auto_20221220_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsettings",
            name="log_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage="django.core.files.storage.FileSystemStorage",
                upload_to="",
            ),
        ),
    ]
