# Generated by Django 4.2.1 on 2023-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0014_alter_projectsettings_log_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentStatus",
        ),
        migrations.DeleteModel(
            name="FileExtensions",
        ),
        migrations.AlterModelOptions(
            name="userrequestslist",
            options={"verbose_name": "request", "verbose_name_plural": "requests"},
        ),
        migrations.AlterField(
            model_name="userrequestslist",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name="userrequestslist",
            table="requests",
        ),
        migrations.DeleteModel(
            name="ProjectSettings",
        ),
        migrations.DeleteModel(
            name="ProjectType",
        ),
    ]
