# Generated by Django 4.2.1 on 2023-05-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("index", "0015_delete_documentstatus_delete_fileextensions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequestslist",
            name="date",
        ),
        migrations.AddField(
            model_name="userrequestslist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="request created date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userrequestslist",
            name="request",
            field=models.CharField(max_length=1000, verbose_name="user request"),
        ),
        migrations.AlterField(
            model_name="userrequestslist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users query",
            ),
        ),
        migrations.AlterField(
            model_name="userrequestslist",
            name="validate_data",
            field=models.JSONField(default=dict, verbose_name="valid data request"),
        ),
    ]
