# Generated by Django 4.2.1 on 2023-05-23 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0017_remove_userrequestslist_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequestslist",
            name="uuid_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
