# Generated by Django 4.2.1 on 2023-05-23 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0018_userrequestslist_uuid_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequestslist",
            name="id",
        ),
        migrations.AlterField(
            model_name="userrequestslist",
            name="uuid_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
