# Generated by Django 4.2.1 on 2023-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0020_rename_uuid_id_userrequestslist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequestslist",
            name="filter_params",
            field=models.JSONField(default=dict, verbose_name="filter params to queryset"),
        ),
    ]
