# Generated by Django 4.2.1 on 2023-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0021_userrequestslist_filter_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequestslist",
            name="request_type",
            field=models.CharField(
                choices=[("PH", "phone request"), ("PR", "person request")],
                default={},
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
