# Generated by Django 3.1.6 on 2021-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.TextField()),
                ('path2base', models.TextField()),
                ('port', models.IntegerField()),
                ('default_log', models.FileField(upload_to='')),
                ('temp_dir', models.TextField()),
            ],
            options={
                'db_table': 'osa_settings',
            },
        ),
    ]
