# Generated by Django 3.1.6 on 2021-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_settings', '0002_auto_20210416_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='osasettings',
            name='records_number_on_page',
            field=models.IntegerField(default=5),
        ),
    ]
