# Generated by Django 3.1.6 on 2022-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_settings', '0003_osasettings_records_number_on_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='osasettings',
            name='archive_path',
            field=models.TextField(default=''),
        ),
    ]
