# Generated by Django 3.1.6 on 2022-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_settings', '0004_osasettings_archive_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='osasettings',
            name='indent',
            field=models.IntegerField(default=100),
        ),
    ]
